cache: pip
dist: xenial
install:
  - yes | pip uninstall py pytest
  - pip install coveralls
jobs:
  include:
    - install: pip install black flake8 pydocstyle sphinx sphinx_rtd_theme .
      python: 3.8
      script:
        - black --check --verbose docs praw tests stubs
        - flake8 --exclude=.eggs,build,docs
        - pydocstyle praw
        - sphinx-build -W docs/ /tmp/foo
      stage: lint
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
script:
  - coverage run --source=praw setup.py test
  - coveralls
stages:
  - lint
  - test
