after_success: coveralls
cache: pip
install: pip install coveralls flake8 pydocstyle
language: python
matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
sudo: false
script:
  - flake8 --exclude=docs
  - pydocstyle praw
  - coverage run --source=praw setup.py test
